### ISSUE TITLE
Invalid file digest type "symlink"

### ISSUE THREAD

**Issue by jorgenpt** [brickadia/p4-fast-reconcile#1] opened 2024-08-09 18:53 UTC
I attempted to use `p4-fast-reconcile` on our depot today. I ran the command on Windows from P4V, as suggested (in dry run mode).

After filtering the workspace, p4-fast-reconcile reports:
```
Error: Invalid file digest type "symlink"
```

and does not complete.

**Comment by jorgenpt** [comment] 2024-08-09 19:08
The digest of a symlink file is the MD5 of the path that it's pointing to. I'm not sure if it's possible to get Windows to create actual links for symlinks from Perforce, but in the default case it is just a text file containing the path of the link.

```
PS C:\dev\project\main> p4 fstat -Rc -Ol //project/main/Tools/Binaries/nodejs/Linux/bin/npx
... depotFile //project/main/Tools/Binaries/nodejs/Linux/bin/npx
... clientFile c:\dev\project\main\Tools\Binaries\nodejs\Linux\bin\npx
... isMapped
... headAction add
... headType symlink
... headTime 1631148009
... headRev 1
... headChange 2740
... headModTime 1630345495
... pathSource //project/v-main
... pathType share
... pathPermissions writable
... effectiveComponentType none
... haveRev 1
... fileSize 39
... digest 851ADF77F5F540BE51E63CBB8F9D11F2

PS C:\dev\project\main> p4 print -q //project/main/Tools/Binaries/nodejs/Linux/bin/npx
../lib/node_modules/npm/bin/npx-cli.js

$ echo '../lib/node_modules/npm/bin/npx-cli.js' | md5sum
851adf77f5f540be51e63cbb8f9d11f2  -
```

**Comment by Zeblote** [comment] 2024-08-09 19:15
Interesting, we do not use symlinks within perforce so I am unable to test this at the moment.

Are these always to files outside of the workspace? What is the intended behavior, should it be marked as edit when the content of the external file changes?

My initial idea would be to
- Add this new type to `DigestType`
- Add it to `impl std::str::FromStr for DigestType`
- Add a new case to `parallel_compute_digests` calling a function similar to `compute_digest_binary` on the underlying file

**Comment by Zeblote** [comment] 2024-08-09 19:48
Oh, it's just the hash of the path. That makes a lot more sense than what I was thinking.

**Closed as completed** 2024-08-19 17:08 UTC
